# ML Engine Configuration

# General Settings
app_name: wazuhai-ml-engine
version: 1.0.0
environment: production
log_level: INFO
log_format: json
log_file: /app/logs/ml-engine.log

# API Settings
api:
  host: 0.0.0.0
  port: 5000
  workers: 4
  timeout: 60
  rate_limit:
    enabled: true
    requests_per_minute: 100
  cors:
    enabled: true
    allowed_origins:
      - https://localhost:5601
      - https://wazuh-manager:55000
  ssl:
    enabled: true
    cert_file: /app/config/ssl/ml-engine.crt
    key_file: /app/config/ssl/ml-engine.key
    ca_file: /app/config/ssl/ca.crt

# Authentication
auth:
  enabled: true
  jwt_secret: ${JWT_SECRET}
  token_expiry: 3600
  api_keys:
    enabled: true
    rotation_days: 30

# Elasticsearch Connection
elasticsearch:
  hosts:
    - http://elasticsearch:9200
  username: elastic
  password: ${ELASTIC_PASSWORD}
  ssl:
    enabled: true
    verify_certs: true
    ca_certs: /app/config/ssl/ca.crt
  timeout: 30
  retry_on_timeout: true
  max_retries: 3

# Model Management
models:
  storage_path: /app/models
  versioning:
    enabled: true
    max_versions: 5
  encryption:
    enabled: true
    key: ${MODEL_ENCRYPTION_KEY}
  backup:
    enabled: true
    frequency: daily
    retention_days: 30
    path: /app/models/backups
  drift_detection:
    enabled: true
    threshold: 0.1
    check_frequency: 3600
    alert_on_drift: true

# Feature Extraction
features:
  user_behavior:
    enabled: true
    window_size: 3600
    features:
      - login_attempts
      - command_execution
      - file_access
      - network_connections
  network_traffic:
    enabled: true
    window_size: 300
    features:
      - packet_count
      - byte_count
      - connection_count
      - protocol_distribution
  system_calls:
    enabled: true
    window_size: 60
    features:
      - syscall_frequency
      - syscall_types
      - process_creation
  command_line:
    enabled: true
    window_size: 3600
    features:
      - command_frequency
      - argument_patterns
      - execution_time

# Model Types
model_types:
  anomaly_detection:
    - isolation_forest
    - autoencoder
    - one_class_svm
  classification:
    - random_forest
    - gradient_boosting
    - neural_network
  time_series:
    - prophet
    - lstm
    - arima

# Training Settings
training:
  batch_size: 64
  epochs: 100
  validation_split: 0.2
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
  hyperparameter_tuning:
    enabled: true
    method: bayesian
    max_trials: 20

# Inference Settings
inference:
  batch_size: 128
  timeout: 30
  max_concurrent: 10
  cache:
    enabled: true
    size: 1000
    ttl: 3600

# Monitoring
monitoring:
  prometheus:
    enabled: true
    port: 8000
  mlflow:
    enabled: true
    tracking_uri: http://mlflow:5000
    experiment_name: wazuhai-ml
  alerts:
    enabled: true
    channels:
      - email
      - slack
    thresholds:
      accuracy: 0.95
      latency: 100
      error_rate: 0.01

# Security
security:
  input_validation:
    enabled: true
    max_input_size: 10485760  # 10MB
  output_sanitization:
    enabled: true
  model_provenance:
    enabled: true
    log_all_operations: true
  access_control:
    enabled: true
    roles:
      - admin
      - analyst
      - viewer 